
---

- hosts: 127.0.0.1
  gather_facts: no

  tasks:
   - name: pkgs
     apt:
       name: 
       - vim
       - i3
       - tcpdump
       - gimp
       - rxvt-unicode
       - xfonts-terminus
       - chromium-browser
       - fbreader
       - feh
       - djview
       - openvpn
       - build-essential
       - mplayer
       - mencoder
       - xchm
       - mupdf
       - smartmontools
       - wget
       - ntfs-3g
       - openssh-server
       - openvpn
       - fbreader
       - dia
       - inkscape
       - mc
       - mutt
       - ghostscript
       - rsync
       - xinit
       - pigz
       - git
       - rar
       - pulseaudio
       - pulseaudio-utils
       - pavucontrol
       - shotwell
       - spice-client-gtk
       - p7zip
# rtorrent
# samba
# vncviewer
# lightdm
# docker
# docker-compose
# rar x
# avrdude
# avr cc
# blueman
# lxc
# fetchmail

       # for monodevelop
      #  - apt-transport-https
      #  - dirmngr
      #  # for unity
      #  - libgconf-2-4

      #  # kvm
      #  - qemu-kvm
      #  - bridge-utils
      #  - libvirt-daemon
      #  - libvirt-daemon-system
      #  - libvirt-clients
      #  - libvirt-doc
      #  - virtinst
       # - libguestfs-tools
       # - oz
       # ganeti
